create table producto
(
    uuid        varchar(100)                               not null
        primary key,
    creadoEn    timestamp      default current_timestamp() not null,
    nombre      varchar(300)                               not null,
    descripcion varchar(1000)                              null,
    precio      decimal(15, 2)                             not null,
    moneda      varchar(5)     default 'Bs.'               not null,
    stock       int                                        not null,
    descuento   decimal(15, 2) default 0.00                not null,
    estado      tinyint(1)                                 not null,
    constraint nombre
        unique (nombre)
);

INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('2fe5ff3e-f808-4e6d-916a-d4959bb87227', '2021-11-24 21:23:23', 'Mesa para exterior o jardin de madera cedro', 'Abada Gen Increpar Incorporal Abadejo Bastonada Engastador Abajadero Abacorar. Geminar Generador Abajo Abacorar Batán Ficticio Cendal Ficha. Cendrazo Cenata Gemoterapia Incrédulo. Engarrafador Batallador Abajeño Incrédulo Abajo Engarrar Cenata Generador. Engarberar Descepar Incorporal Incordio Gemoso Incredibilidad Fichar Fice Ceneque Gemiquear.
', 700.00, 'Bs.', 11, 3.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('5e916855-3d48-46b5-b2ab-47cffea85be7', '2021-11-24 21:20:49', 'Marco de madera de abeto para interior y exteriror', 'Abada Gen Increpar Incorporal Abadejo Bastonada Engastador Abajadero Abacorar. Geminar Generador Abajo Abacorar Batán Ficticio Cendal Ficha. Cendrazo Cenata Gemoterapia Incrédulo. Engarrafador Batallador Abajeño Incrédulo Abajo Engarrar Cenata Generador. Engarberar Descepar Incorporal Incordio Gemoso Incredibilidad Fichar Fice Ceneque Gemiquear.
', 700.00, 'Bs.', 9, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('7307299d-ec02-4f52-98d0-baf027033698', '2022-03-11 20:09:44', 'Puerta de cedro para interiores', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo beatae quisquam, optio eligendi atque dicta minima labore dolor odio? Ex quos vel aliquid possimus officia obcaecati harum repellat autem quo!', 100.00, 'Bs.', 4, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('7380f463-deb1-40ce-9f4f-7f5a959b6e32', '2022-03-11 14:56:40', 'Escaleras de madera Tradicionales', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo beatae quisquam, optio eligendi atque dicta minima labore dolor odio? Ex quos vel aliquid possimus officia obcaecati harum repellat autem quo!', 400.00, 'Bs.', 13, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('7d9ca4bb-b259-4ce2-b069-4893f074b597', '2021-11-27 22:14:26', 'Vitrina de madera de abeto matrimonial con cajuelas amplias', 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque debitis quibusdam laborum adipisci dolorem sunt provident, in eaque deleniti sequi? Quasi iure accusantium voluptas odio, maxime fugit perferendis ipsum reiciendis?', 1000.00, 'Bs.', 0, 3.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('7e92e09b-7a2a-44ba-b2c9-21a0bc9b7d63', '2022-03-11 15:04:58', 'Mesa de madera de pino 4m x 4m', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo beatae quisquam, optio eligendi atque dicta minima labore dolor odio? Ex quos vel aliquid possimus officia obcaecati harum repellat autem quo!', 150.00, 'Bs.', 4, 40.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('890d6295-ad7a-481f-acf0-c608c5e7a9df', '2021-11-24 21:17:14', 'Escaleras de madera de abeto para interior', 'Abada Gen Increpar Incorporal Abadejo Bastonada Engastador Abajadero Abacorar. Geminar Generador Abajo Abacorar Batán Ficticio Cendal Ficha. Cendrazo Cenata Gemoterapia Incrédulo. Engarrafador Batallador Abajeño Incrédulo Abajo Engarrar Cenata Generador. Engarberar Descepar Incorporal Incordio Gemoso Incredibilidad Fichar Fice Ceneque Gemiquear.', 5000.00, 'Bs.', 6, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('ad8325f8-1f19-4364-8a1f-0d85732d7d71', '2021-11-24 21:26:25', 'Sillas de madera de nogal para interior con un diseño clasico', 'Abada Gen Increpar Incorporal Abadejo Bastonada Engastador Abajadero Abacorar. Geminar Generador Abajo Abacorar Batán Ficticio Cendal Ficha. Cendrazo Cenata Gemoterapia Incrédulo. Engarrafador Batallador Abajeño Incrédulo Abajo Engarrar Cenata Generador. Engarberar Descepar Incorporal Incordio Gemoso Incredibilidad Fichar Fice Ceneque Gemiquear.
', 200.00, 'Bs.', 103, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('b84f59d3-650e-4cb6-815d-cec6bfc49ac0', '2022-03-11 14:57:42', 'Escaleras minimalistas para interior', '', 1000.00, 'Bs.', 8, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('ec428dc7-a821-4b21-b16b-c9f98f88687c', '2021-11-24 21:19:44', 'Marco de ventana de madera de pino reforzado para exterior', 'Abada Gen Increpar Incorporal Abadejo Bastonada Engastador Abajadero Abacorar. Geminar Generador Abajo Abacorar Batán Ficticio Cendal Ficha. Cendrazo Cenata Gemoterapia Incrédulo. Engarrafador Batallador Abajeño Incrédulo Abajo Engarrar Cenata Generador. Engarberar Descepar Incorporal Incordio Gemoso Incredibilidad Fichar Fice Ceneque Gemiquear.
', 500.00, 'Bs.', 43, 5.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('fa97335b-3efd-499d-9ec2-78c49597a301', '2022-03-11 14:59:06', 'Escaleras para exterior con disenho minimalista de madera de pino', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo beatae quisquam, optio eligendi atque dicta minima labore dolor odio? Ex quos vel aliquid possimus officia obcaecati harum repellat autem quo!', 300.00, 'Bs.', 10, 0.00, 1);
