create table producto
(
    uuid        varchar(100)                               not null
        primary key,
    creadoEn    timestamp      default current_timestamp() not null,
    nombre      varchar(300)                               not null,
    descripcion text                                       null,
    precio      decimal(15, 2)                             not null,
    moneda      varchar(5)     default 'Bs.'               not null,
    stock       int                                        not null,
    descuento   decimal(15, 2) default 0.00                not null,
    estado      tinyint(1)                                 not null,
    constraint nombre
        unique (nombre)
);

INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('0050a1a6-1ee2-4ad7-9685-8b8e6292e277', '2022-05-26 14:00:05', 'Escritorio para computadora con base para teclado con dos cajones y repisas', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Escritorio para computadora con base para teclado con dos cajones y repisas</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('006fe36f-1f53-49c6-b5d6-5dcca6571d42', '2022-05-27 00:25:26', 'puerta principal de doble hoja con jaladores de aluminio (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 1.10<div><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Doble hoja con jaladores de aluminio<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 1407.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('02cea732-e77c-4546-b841-0fd048f15d0c', '2022-05-26 14:36:22', 'Mueble de recepción con cajones y puertas con vidrio templado en la parte superior', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Mueble de recepción con cajones y puertas con vidrio templado en la parte superior</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('03819ff5-84a4-4bf2-bb23-fea2ca888a6f', '2022-05-25 16:07:40', 'Repisa para computadora con base para teclado con dos cajones y repisas', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Escritorio para computadora con base para teclado con dos cajones y repisas</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('208dbcc3-caeb-401a-aec2-03c97db83495', '2022-05-26 14:05:11', 'Escritorio múltiple con cajones y jaladores de aluminio ', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Escritorio múltiple con cajones y jaladores de aluminio</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('24a102fe-58cf-4de1-9063-1db1c75d9eb4', '2022-05-27 22:41:17', 'puerta acabado maciza con diseño especial (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 0.90<br><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta con diseño especial<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div>', 1436.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('36d2421b-cbae-4dd3-aac7-4544efc9d6af', '2022-05-25 16:04:12', 'Mesa de reunión de 5 sillas con enchufe en el centro', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Mesa de 5 sillas con enchufe en el centro</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('410b5731-4c04-4262-a734-b5c03c140569', '2022-05-27 10:29:12', 'puerta principal de doble hoja, 6 divisiones, aluminio o vidrio templado entre división (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 1.20<div><div><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta doble hoja, 6 divisiones, aluminio o vidrio templado entre división<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div></div>', 1925.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('447bac09-6ed6-48cb-9d43-321833b91eee', '2022-05-27 22:31:17', 'puerta acabado maciza de 3 divisiones (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 0.90<br><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta 3 divisiones<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div>', 1507.00, 'Bs.', 1000, 7.30, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('4d6712b0-c7f5-48f2-bfa5-305e8a766781', '2022-05-25 14:10:24', 'Mueble Odontológico con cajones y puertas batientes, jaladores de sobreponer y mampara', '<li><b>MATERIAL</b><br></li>Madera y aglomerado<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Puerta&nbsp; doble hoja con 6 divisiones, con vidrio opacid o aluminios</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('72668ec0-19d6-4062-9477-45623f4f3f9a', '2022-05-26 14:13:32', 'Escritorio múltiple cajonería alta con vidrio opacid en la parte inferior dos cajones con base para computadora y teclado', '<li><b>MATERIAL</b><br></li>Melamina con vidrio opacid<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Escritorio múltiple cajonería alta con vidrio opacid en la parte inferior dos cajones con base para computadora y teclado</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('7bd5774f-6174-48a9-b456-ed132353885a', '2022-05-27 23:18:40', 'puerta principal de 9 disiones con tragaluz lateral, superior vidrio (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>Puerta: 2.10 x 0.90<div>Tragaluz: 2.50 x 0.80<br><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta 9 divisiones con tragaluz lateral, superior vidrio<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 1407.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('95925ddf-95ff-4e5e-82a8-8d98cb5c7790', '2022-05-26 15:50:24', 'Mueble de recepción con cajones y puertas con granito en la parte superior con base para computadora', '<li><b>MATERIAL</b><br></li>Melamina<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Mueble de recepción con cajones y puertas con granito en la parte superior con base para computadora</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('a35424cc-fd28-44ac-a604-4c4b2d628f43', '2022-05-27 13:48:46', 'puerta principal de doble hoja con 6 divisiones y vidrio opacid o aluminio (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 1.10<div><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta&nbsp; doble hoja con 6 divisiones, con vidrio opacid o aluminios<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 1851.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('b1cb4347-9792-4454-b9f6-a8b5db3e9ee9', '2022-05-26 14:31:47', 'Escritorio ejecutivo de 3 cajones con vidrio templado sobre el escritorio y vidrio templado en la parte frontal', '<li><b>MATERIAL</b><br></li>Trupan con vidrio templado<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>3 cajones con vidrio templado sobre el escritorio y vidrio templado en la parte frontal</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('b30ac8ef-ad14-477e-9f57-0fa0eba5d71d', '2022-05-27 10:20:17', 'puerta principal de doble hoja, tragaluz superior (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>Puerta: 2.10 x 1.20<div>Tragaluz: 0.40 x 1.20<br><div><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta doble hoja, tragaluz superior<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div></div>', 1682.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('c05c67f9-8333-4c0b-b170-4929a2661085', '2022-05-26 14:08:08', 'Escritorio múltiple diversos colores con base para computadora y teclado en la parte superior repisa', '<li><b>MATERIAL</b><br></li>Trupan<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Escritorio múltiple diversos colores con base para computadora y teclado en la parte superior repisa para documentos</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('cb099636-c1c2-44d5-8c25-8d18cf619e23', '2022-05-27 12:25:43', 'puerta principal de Puerta  6 divisiones, con vidrio opacid o aluminios (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 0.90<div><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta&nbsp; 6 divisiones, con vidrio opacid o aluminios<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 1368.00, 'Bs.', 1000, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('ce1c1bf2-d9a1-449d-a02b-9b3f220f1dbb', '2022-05-27 17:40:15', 'puerta acabado maciza de 5 divisiones (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 0.90<br><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta 5 divisiones<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div>', 1507.00, 'Bs.', 1000, 7.30, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('d6741f11-aa21-486a-817f-1d516c452da1', '2022-05-25 15:40:23', 'Mesa de 12 sillas con enchufe empotrado en el centro', '<li><b>MATERIAL</b><br></li>Madera maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Mesa estática de 12 sillas con enchufe empotrado en el centro</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('decda335-f5d2-4987-96bf-79794f1462ab', '2022-05-27 22:27:02', 'puerta acabado maciza de 11 divisiones (maramacho)', '<li><b>MATERIAL</b><br></li>Maramacho<li><b>COLOR&nbsp;</b><br></li>A elección<br><li><b>DIMENSIONES&nbsp;</b>(Minimas Recomendadas)<br></li>2.10 x 0.90<br><li><b>ESPESOR</b><br></li>2 Pulgadas<br><li><b>DETALLE</b><br></li>Puerta 11 divisiones<br><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div>', 1507.00, 'Bs.', 1000, 7.30, 1);
INSERT INTO mendozarq.producto (uuid, creadoEn, nombre, descripcion, precio, moneda, stock, descuento, estado) VALUES ('fdf00dc4-cb2b-42a0-9b63-46132723946b', '2022-05-26 14:20:19', 'Mueble de recepción con cajones y puertas con vidrio templado en la parte superior y cinta led', '<li><b>MATERIAL</b><br></li>Trupan<li><b>COLOR&nbsp;</b><br></li>A elección<div><li><b>DETALLE</b><br></li>Mueble de recepción con cajones y puertas con vidrio templado en la parte superior y cinta led</div><div><div><font color="#ff0000"><b>* Fabricamos a medida, espesor, color y madera a gusto del</b></font></div><div><font color="#ff0000"><b>cliente.</b></font></div></div>', 0.00, 'Bs.', 0, 0.00, 1);
